name       : protobuf
version    : 3.0.0
release    : 5
source     :
    - https://github.com/google/protobuf/archive/v3.0.0.tar.gz : f5b3563f118f1d3d6e001705fa7082e8fc3bda50038ac3dff787650795734146
homepage   : https://developers.google.com/protocol-buffers/
license    :
    - GPLv2+
component  : programming
summary    : Protocol Buffers - Google's data interchange format
description: |
    Protocol Buffers - Google's data interchange format
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
