name       : protobuf
version    : '21.12'
release    : 15
source     :
    - https://github.com/protocolbuffers/protobuf/archive/refs/tags/v21.12.tar.gz : 22fdaf641b31655d4b2297f9981fa5203b2866f8332d3c6333f6b0107bb320de
homepage   : https://developers.google.com/protocol-buffers/
license    : BSD-3-Clause
component  : programming
summary    : Protocol Buffers - Google's data interchange format
description: |
    Protocol Buffers - Google's data interchange format
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
