name       : protobuf
version    : 3.17.3
release    : 13
source     :
    - https://github.com/protocolbuffers/protobuf/archive/refs/tags/v3.17.3.tar.gz : c6003e1d2e7fefa78a3039f19f383b4f3a61e81be8c19356f85b6461998ad3db
homepage   : https://developers.google.com/protocol-buffers/
license    : BSD-3-Clause
component  : programming
summary    : Protocol Buffers - Google's data interchange format
description: |
    Protocol Buffers - Google's data interchange format
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
