name       : protobuf
version    : 3.5.1
release    : 7
source     :
    - https://github.com/google/protobuf/archive/v3.5.1.tar.gz : 826425182ee43990731217b917c5c3ea7190cfda141af4869e6d4ad9085a740f
homepage   : https://developers.google.com/protocol-buffers/
license    : BSD-3-Clause
component  : programming
summary    : Protocol Buffers - Google's data interchange format
description: |
    Protocol Buffers - Google's data interchange format
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
