name       : protobuf
version    : '21.6'
release    : 14
source     :
    - https://github.com/protocolbuffers/protobuf/archive/refs/tags/v21.6.tar.gz : dbb16fdbca8f277c9a194d9a837395cde408ca136738d94743130dd0de015efd
homepage   : https://developers.google.com/protocol-buffers/
license    : BSD-3-Clause
component  : programming
summary    : Protocol Buffers - Google's data interchange format
description: |
    Protocol Buffers - Google's data interchange format
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
