name        : protobuf
version     : 2.6.1
release     : 3
source      :
    - https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.bz2 : ee445612d544d885ae240ffbcbf9267faa9f593b7b101f21d58beceb92661910
homepage    : https://developers.google.com/protocol-buffers/
license     :
    - GPLv2+
summary     : Protocol Buffers - Google's data interchange format
description : |
    Protocol Buffers - Google's data interchange format
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
